client_config_backend: settings
client_config:
  client_id: 507217153408-l744aufduqo854btd0bkq953egvicop2.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive